### ISSUE TITLE
Incorrect metadata for HLS content

### ISSUE THREAD

**Issue by mfeingol** [plexinc-plugins/PBS.bundle#21]
The container should be mpegts, not mp4.

E.g. Featured Shows > Austin City Limits > Rodrigo y Gabriela

```
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer mediaTagVersion="1418763535" mediaTagPrefix="/system/bundle/media/flags/" identifier="com.plexapp.system" size="1">
<Video type="clip" key="http://ga.video.cdn.pbs.org/videos/austin-city-limits/b4cd5c02-52e2-41dc-9fef-307104bb0b3d/53658/hd-mezzanine-16x9/aucl3807_mezz16x9-16x9-hls-low_521.m3u8" sourceIcon="http://resources-cdn.plexapp.com/image/source/com.plexapp.plugins.pbs.jpg?h=0d8b4a8">
<Media videoCodec="h264" audioCodec="aac" container="mp4" optimizedForStreaming="1" protocol="hls" audioChannels="2">
<Part key="http://ga.video.cdn.pbs.org/videos/austin-city-limits/b4cd5c02-52e2-41dc-9fef-307104bb0b3d/53658/hd-mezzanine-16x9/aucl3807_mezz16x9-16x9-hls-low_521.m3u8" container="mp4" optimizedForStreaming="1" file="">
<Stream id="1" codec="h264" streamType="1" selected="1" index="0"/>
<Stream id="2" codec="aac" streamType="2" selected="1" index="1" channels="2"/>
</Part>
</Media>
</Video>
</MediaContainer>
```

**Comment by Gerk** [comment]
I think this is set in the main Services.bundle 

https://github.com/plexinc-plugins/Services.bundle/blob/master/Contents/Service%20Sets/com.plexapp.plugins.pbs/URL/PBS/ServiceCode.pys#L43

Is this just to the HLS stream or for actual mp4 files as well? (this channel can serve up both but only blindly sets the container before it knows which is which)

**Comment by mfeingol** [comment]
Not sure I'm parsing your question correctly...  But In this case there are no mp4 files involved.  Just an HLS stream, whose files appear to be mpegts/h264/aac.

This isn't a P0 since most apps will just chase the m3u8 anyway, and it will work.  But I'm a stickler for correct media information where possible...

**Comment by Gerk** [comment]
Figuring out which is which before actually jumping through a lot of hoops and making several http calls is pretty much impossible, would we be better off to just not declare a container there in terms of client handling?  I think at one point @jam said it was better to have something (even if it's not correct) than nothing ...

**Comment by mfeingol** [comment]
I don't honestly know...  That probably depends on the client, sadly.

In this case, could we not look at the part key and see if it's an HLS URL, and then set the container accordingly?

**Comment by Gerk** [comment]
The issue is that with the channel framework we should not be making HTTP calls when setting the MediaObject information -- these happen when any Objects are initially listed, like in a grid/text view in the client.  If we did try and do HTTP requests at this point list building in the clients would be incredibly slow (to the point that they might even time out).  We only do those lookups when the file is actually "played" by the client -- so only at that point do we know if it's HLS or direct mp4 in these cases.

**Comment by mfeingol** [comment]
I wonder if maybe when the guess is likely to be wrong, the initial indirect container shouldn't have media info - as you were suggesting.

Then presumably the resolved media container can have correct media info?

**Comment by Gerk** [comment]
It should be removed now, not sure how long it will take to hit the streets
