### ISSUE TITLE
No audio when streaming to Chromecast

### ISSUE THREAD

**Issue by himenohogosha** [plexinc-plugins/PBS.bundle#25]
When I view the Plex PBS channel on desktop or laptop, I have no problems with the video. However, when I attempt to send the video to my Chromecast I only get video with no sound. 

Plex version 2.3.24
Server version 0.9.11.16

**Comment by shopgirl284** [comment]
This issue should be closed. 

Since the plugin has been completely rewritten and the code is new, past issues are no longer applicable
