### ISSUE TITLE
Not showing up in search

### ISSUE THREAD

**Issue by lackita** [plexinc-plugins/PBS.bundle#31]
When I perform a search, results from the plugin aren't included.

**Comment by sander1** [comment]
The channel code has been updated very recently, but the search service hasn't been touched. I'm looking into that, it might be broken as well. Also, I've just learned that some Plex clients do not include search results from channels in searches (the web client for example does not).

**Comment by lackita** [comment]
Oh, I didn't realize the web client excludes those results. That's where I was trying it.
